/**
 * Build-identity stamping helpers.
 *
 * Release evidence depends on the deployed runtime serving the exact
 * GITHUB_SHA at /runtime-build-id.txt. These helpers are pure so the
 * failure mode (a stale committed `local-development` identity being
 * copied into the deployed asset directory, or the identity asset being
 * cached) can be covered by regression tests.
 */

export const LOCAL_BUILD_ID = "local-development";

export const BUILD_ID_ASSET = "runtime-build-id.txt";

export const BUILD_ID_NO_STORE_RULE = `/${BUILD_ID_ASSET}\n  Cache-Control: no-store, no-cache, must-revalidate\n`;

/**
 * Resolve the authoritative build identity.
 *
 * A CI-provided GITHUB_SHA ALWAYS wins over any existing on-disk value.
 * This is the defect that caused Runtime Test Deploy #616: the repository
 * contains `public/runtime-build-id.txt` with `local-development`, so an
 * "only write when missing" strategy silently deployed the stale identity.
 */
export function resolveBuildId(
  githubSha: string | undefined,
  existingContent: string | undefined,
): string {
  const sha = githubSha?.trim();
  if (sha) return sha;
  const existing = existingContent?.trim();
  if (existing) return existing;
  return LOCAL_BUILD_ID;
}

/** True when the stamped identity is a real release identity (not a local build). */
export function isStampedReleaseIdentity(buildId: string): boolean {
  return buildId.trim().length > 0 && buildId.trim() !== LOCAL_BUILD_ID;
}

/**
 * Merge the no-store rule for the identity asset into an existing
 * Cloudflare `_headers` file without discarding rules generated by the
 * build (e.g. the immutable rule for hashed /assets/*).
 */
export function mergeNoStoreHeaderRule(existingHeaders: string | undefined): string {
  const existing = (existingHeaders ?? "").replace(/\s+$/, "");
  if (existing.includes(`/${BUILD_ID_ASSET}`)) {
    return `${existing}\n`;
  }
  if (existing.length === 0) {
    return BUILD_ID_NO_STORE_RULE;
  }
  return `${existing}\n\n${BUILD_ID_NO_STORE_RULE}`;
}
