/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ControlRouteImport } from './routes/control'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FoodRouteImport } from './routes/food'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanWeekRouteImport } from './routes/plan-week'
import { Route as RuntimeHouseholdRouteImport } from './routes/runtime-household'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SweepRouteImport } from './routes/sweep'
import { Route as SystemRouteImport } from './routes/system'
import { Route as WeekRouteImport } from './routes/week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanWeekRoute = PlanWeekRouteImport.update({
  id: '/plan-week',
  path: '/plan-week',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeHouseholdRoute = RuntimeHouseholdRouteImport.update({
  id: '/runtime-household',
  path: '/runtime-household',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepRoute = SweepRouteImport.update({
  id: '/sweep',
  path: '/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/control': typeof ControlRoute
  '/cycle': typeof CycleRoute
  '/delivery': typeof DeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-week': typeof PlanWeekRoute
  '/runtime-household': typeof RuntimeHouseholdRoute
  '/shop': typeof ShopRoute
  '/stock': typeof StockRoute
  '/sweep': typeof SweepRoute
  '/system': typeof SystemRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/control': typeof ControlRoute
  '/cycle': typeof CycleRoute
  '/delivery': typeof DeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-week': typeof PlanWeekRoute
  '/runtime-household': typeof RuntimeHouseholdRoute
  '/shop': typeof ShopRoute
  '/stock': typeof StockRoute
  '/sweep': typeof SweepRoute
  '/system': typeof SystemRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/control': typeof ControlRoute
  '/cycle': typeof CycleRoute
  '/delivery': typeof DeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-week': typeof PlanWeekRoute
  '/runtime-household': typeof RuntimeHouseholdRoute
  '/shop': typeof ShopRoute
  '/stock': typeof StockRoute
  '/sweep': typeof SweepRoute
  '/system': typeof SystemRoute
  '/week': typeof WeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/control'
    | '/cycle'
    | '/delivery'
    | '/feedback'
    | '/food'
    | '/onboarding'
    | '/plan-week'
    | '/runtime-household'
    | '/shop'
    | '/stock'
    | '/sweep'
    | '/system'
    | '/week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/control'
    | '/cycle'
    | '/delivery'
    | '/feedback'
    | '/food'
    | '/onboarding'
    | '/plan-week'
    | '/runtime-household'
    | '/shop'
    | '/stock'
    | '/sweep'
    | '/system'
    | '/week'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/control'
    | '/cycle'
    | '/delivery'
    | '/feedback'
    | '/food'
    | '/onboarding'
    | '/plan-week'
    | '/runtime-household'
    | '/shop'
    | '/stock'
    | '/sweep'
    | '/system'
    | '/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  ControlRoute: typeof ControlRoute
  CycleRoute: typeof CycleRoute
  DeliveryRoute: typeof DeliveryRoute
  FeedbackRoute: typeof FeedbackRoute
  FoodRoute: typeof FoodRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanWeekRoute: typeof PlanWeekRoute
  RuntimeHouseholdRoute: typeof RuntimeHouseholdRoute
  ShopRoute: typeof ShopRoute
  StockRoute: typeof StockRoute
  SweepRoute: typeof SweepRoute
  SystemRoute: typeof SystemRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-week': {
      id: '/plan-week'
      path: '/plan-week'
      fullPath: '/plan-week'
      preLoaderRoute: typeof PlanWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-household': {
      id: '/runtime-household'
      path: '/runtime-household'
      fullPath: '/runtime-household'
      preLoaderRoute: typeof RuntimeHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweep': {
      id: '/sweep'
      path: '/sweep'
      fullPath: '/sweep'
      preLoaderRoute: typeof SweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  ControlRoute: ControlRoute,
  CycleRoute: CycleRoute,
  DeliveryRoute: DeliveryRoute,
  FeedbackRoute: FeedbackRoute,
  FoodRoute: FoodRoute,
  OnboardingRoute: OnboardingRoute,
  PlanWeekRoute: PlanWeekRoute,
  RuntimeHouseholdRoute: RuntimeHouseholdRoute,
  ShopRoute: ShopRoute,
  StockRoute: StockRoute,
  SweepRoute: SweepRoute,
  SystemRoute: SystemRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
